// Code generated by protoc-gen-go. DO NOT EDIT.
// source: KeyWithStringValue.proto

package protocol

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KeyWithStringValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyWithStringValue) Reset()         { *m = KeyWithStringValue{} }
func (m *KeyWithStringValue) String() string { return proto.CompactTextString(m) }
func (*KeyWithStringValue) ProtoMessage()    {}
func (*KeyWithStringValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_49decc28718dec97, []int{0}
}

func (m *KeyWithStringValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyWithStringValue.Unmarshal(m, b)
}
func (m *KeyWithStringValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyWithStringValue.Marshal(b, m, deterministic)
}
func (m *KeyWithStringValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyWithStringValue.Merge(m, src)
}
func (m *KeyWithStringValue) XXX_Size() int {
	return xxx_messageInfo_KeyWithStringValue.Size(m)
}
func (m *KeyWithStringValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyWithStringValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyWithStringValue proto.InternalMessageInfo

func (m *KeyWithStringValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyWithStringValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*KeyWithStringValue)(nil), "KeyWithStringValue")
}

func init() { proto.RegisterFile("KeyWithStringValue.proto", fileDescriptor_49decc28718dec97) }

var fileDescriptor_49decc28718dec97 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xf0, 0x4e, 0xad, 0x0c,
	0xcf, 0x2c, 0xc9, 0x08, 0x2e, 0x29, 0xca, 0xcc, 0x4b, 0x0f, 0x4b, 0xcc, 0x29, 0x4d, 0xd5, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x57, 0xb2, 0xe1, 0x12, 0xc2, 0x94, 0x13, 0x12, 0xe0, 0x62, 0xce, 0x4e,
	0xad, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x85, 0x44, 0xb8, 0x58, 0xcb, 0x40,
	0x52, 0x12, 0x4c, 0x60, 0x31, 0x08, 0xc7, 0xc9, 0x83, 0x4b, 0x3d, 0xbf, 0x28, 0x5d, 0x2f, 0xb1,
	0x20, 0x31, 0x39, 0x23, 0x55, 0xaf, 0x38, 0xbb, 0xb2, 0x3c, 0x31, 0x27, 0x3b, 0x33, 0x0f, 0x24,
	0x92, 0xab, 0x97, 0x97, 0x5a, 0x52, 0x9e, 0x5f, 0x94, 0x0d, 0xb1, 0x28, 0x80, 0x71, 0x15, 0x93,
	0x54, 0x70, 0x76, 0x65, 0x38, 0x54, 0x81, 0x1f, 0x44, 0x32, 0x00, 0x24, 0x97, 0x9c, 0x9f, 0x93,
	0xc4, 0x06, 0x56, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x80, 0xb0, 0x3e, 0xe2, 0xaa, 0x00,
	0x00, 0x00,
}
