// Code generated by protoc-gen-go. DO NOT EDIT.
// source: KeyWithIntegerValue.proto

package protocol

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KeyWithIntegerValue struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                int32    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyWithIntegerValue) Reset()         { *m = KeyWithIntegerValue{} }
func (m *KeyWithIntegerValue) String() string { return proto.CompactTextString(m) }
func (*KeyWithIntegerValue) ProtoMessage()    {}
func (*KeyWithIntegerValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_b289a5dcc1bb229e, []int{0}
}

func (m *KeyWithIntegerValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyWithIntegerValue.Unmarshal(m, b)
}
func (m *KeyWithIntegerValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyWithIntegerValue.Marshal(b, m, deterministic)
}
func (m *KeyWithIntegerValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyWithIntegerValue.Merge(m, src)
}
func (m *KeyWithIntegerValue) XXX_Size() int {
	return xxx_messageInfo_KeyWithIntegerValue.Size(m)
}
func (m *KeyWithIntegerValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyWithIntegerValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyWithIntegerValue proto.InternalMessageInfo

func (m *KeyWithIntegerValue) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KeyWithIntegerValue) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*KeyWithIntegerValue)(nil), "KeyWithIntegerValue")
}

func init() { proto.RegisterFile("KeyWithIntegerValue.proto", fileDescriptor_b289a5dcc1bb229e) }

var fileDescriptor_b289a5dcc1bb229e = []byte{
	// 94 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xf4, 0x4e, 0xad, 0x0c,
	0xcf, 0x2c, 0xc9, 0xf0, 0xcc, 0x2b, 0x49, 0x4d, 0x4f, 0x2d, 0x0a, 0x4b, 0xcc, 0x29, 0x4d, 0xd5,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xb2, 0xe5, 0x12, 0xc6, 0x22, 0x29, 0x24, 0xc0, 0xc5, 0x9c,
	0x9d, 0x5a, 0x29, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x62, 0x0a, 0x89, 0x70, 0xb1, 0x96,
	0x81, 0xa4, 0x24, 0x98, 0x14, 0x18, 0x35, 0x58, 0x83, 0x20, 0x9c, 0x24, 0x36, 0xb0, 0x29, 0xc6,
	0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x58, 0x27, 0xd7, 0xb2, 0x62, 0x00, 0x00, 0x00,
}
