// Code generated by protoc-gen-go. DO NOT EDIT.
// source: TraceSegmentService.proto

package protocol

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RefType int32

const (
	RefType_CrossProcess RefType = 0
	RefType_CrossThread  RefType = 1
)

var RefType_name = map[int32]string{
	0: "CrossProcess",
	1: "CrossThread",
}

var RefType_value = map[string]int32{
	"CrossProcess": 0,
	"CrossThread":  1,
}

func (x RefType) String() string {
	return proto.EnumName(RefType_name, int32(x))
}

func (RefType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bc055cab3bd8ed31, []int{0}
}

type SpanLayer int32

const (
	SpanLayer_Unknown      SpanLayer = 0
	SpanLayer_Database     SpanLayer = 1
	SpanLayer_RPCFramework SpanLayer = 2
	SpanLayer_Http         SpanLayer = 3
	SpanLayer_MQ           SpanLayer = 4
	SpanLayer_Cache        SpanLayer = 5
)

var SpanLayer_name = map[int32]string{
	0: "Unknown",
	1: "Database",
	2: "RPCFramework",
	3: "Http",
	4: "MQ",
	5: "Cache",
}

var SpanLayer_value = map[string]int32{
	"Unknown":      0,
	"Database":     1,
	"RPCFramework": 2,
	"Http":         3,
	"MQ":           4,
	"Cache":        5,
}

func (x SpanLayer) String() string {
	return proto.EnumName(SpanLayer_name, int32(x))
}

func (SpanLayer) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bc055cab3bd8ed31, []int{1}
}

type UpstreamSegment struct {
	GlobalTraceIds       []*UniqueId `protobuf:"bytes,1,rep,name=globalTraceIds,proto3" json:"globalTraceIds,omitempty"`
	Segment              []byte      `protobuf:"bytes,2,opt,name=segment,proto3" json:"segment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpstreamSegment) Reset()         { *m = UpstreamSegment{} }
func (m *UpstreamSegment) String() string { return proto.CompactTextString(m) }
func (*UpstreamSegment) ProtoMessage()    {}
func (*UpstreamSegment) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc055cab3bd8ed31, []int{0}
}

func (m *UpstreamSegment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpstreamSegment.Unmarshal(m, b)
}
func (m *UpstreamSegment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpstreamSegment.Marshal(b, m, deterministic)
}
func (m *UpstreamSegment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpstreamSegment.Merge(m, src)
}
func (m *UpstreamSegment) XXX_Size() int {
	return xxx_messageInfo_UpstreamSegment.Size(m)
}
func (m *UpstreamSegment) XXX_DiscardUnknown() {
	xxx_messageInfo_UpstreamSegment.DiscardUnknown(m)
}

var xxx_messageInfo_UpstreamSegment proto.InternalMessageInfo

func (m *UpstreamSegment) GetGlobalTraceIds() []*UniqueId {
	if m != nil {
		return m.GlobalTraceIds
	}
	return nil
}

func (m *UpstreamSegment) GetSegment() []byte {
	if m != nil {
		return m.Segment
	}
	return nil
}

type UniqueId struct {
	IdParts              []int64  `protobuf:"varint,1,rep,packed,name=idParts,proto3" json:"idParts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UniqueId) Reset()         { *m = UniqueId{} }
func (m *UniqueId) String() string { return proto.CompactTextString(m) }
func (*UniqueId) ProtoMessage()    {}
func (*UniqueId) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc055cab3bd8ed31, []int{1}
}

func (m *UniqueId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UniqueId.Unmarshal(m, b)
}
func (m *UniqueId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UniqueId.Marshal(b, m, deterministic)
}
func (m *UniqueId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UniqueId.Merge(m, src)
}
func (m *UniqueId) XXX_Size() int {
	return xxx_messageInfo_UniqueId.Size(m)
}
func (m *UniqueId) XXX_DiscardUnknown() {
	xxx_messageInfo_UniqueId.DiscardUnknown(m)
}

var xxx_messageInfo_UniqueId proto.InternalMessageInfo

func (m *UniqueId) GetIdParts() []int64 {
	if m != nil {
		return m.IdParts
	}
	return nil
}

type TraceSegmentObject struct {
	TraceSegmentId        *UniqueId     `protobuf:"bytes,1,opt,name=traceSegmentId,proto3" json:"traceSegmentId,omitempty"`
	Spans                 []*SpanObject `protobuf:"bytes,2,rep,name=spans,proto3" json:"spans,omitempty"`
	ApplicationId         int32         `protobuf:"varint,3,opt,name=applicationId,proto3" json:"applicationId,omitempty"`
	ApplicationInstanceId int32         `protobuf:"varint,4,opt,name=applicationInstanceId,proto3" json:"applicationInstanceId,omitempty"`
	IsSizeLimited         bool          `protobuf:"varint,5,opt,name=isSizeLimited,proto3" json:"isSizeLimited,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}      `json:"-"`
	XXX_unrecognized      []byte        `json:"-"`
	XXX_sizecache         int32         `json:"-"`
}

func (m *TraceSegmentObject) Reset()         { *m = TraceSegmentObject{} }
func (m *TraceSegmentObject) String() string { return proto.CompactTextString(m) }
func (*TraceSegmentObject) ProtoMessage()    {}
func (*TraceSegmentObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc055cab3bd8ed31, []int{2}
}

func (m *TraceSegmentObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TraceSegmentObject.Unmarshal(m, b)
}
func (m *TraceSegmentObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TraceSegmentObject.Marshal(b, m, deterministic)
}
func (m *TraceSegmentObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraceSegmentObject.Merge(m, src)
}
func (m *TraceSegmentObject) XXX_Size() int {
	return xxx_messageInfo_TraceSegmentObject.Size(m)
}
func (m *TraceSegmentObject) XXX_DiscardUnknown() {
	xxx_messageInfo_TraceSegmentObject.DiscardUnknown(m)
}

var xxx_messageInfo_TraceSegmentObject proto.InternalMessageInfo

func (m *TraceSegmentObject) GetTraceSegmentId() *UniqueId {
	if m != nil {
		return m.TraceSegmentId
	}
	return nil
}

func (m *TraceSegmentObject) GetSpans() []*SpanObject {
	if m != nil {
		return m.Spans
	}
	return nil
}

func (m *TraceSegmentObject) GetApplicationId() int32 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *TraceSegmentObject) GetApplicationInstanceId() int32 {
	if m != nil {
		return m.ApplicationInstanceId
	}
	return 0
}

func (m *TraceSegmentObject) GetIsSizeLimited() bool {
	if m != nil {
		return m.IsSizeLimited
	}
	return false
}

type TraceSegmentReference struct {
	RefType                     RefType   `protobuf:"varint,1,opt,name=refType,proto3,enum=RefType" json:"refType,omitempty"`
	ParentTraceSegmentId        *UniqueId `protobuf:"bytes,2,opt,name=parentTraceSegmentId,proto3" json:"parentTraceSegmentId,omitempty"`
	ParentSpanId                int32     `protobuf:"varint,3,opt,name=parentSpanId,proto3" json:"parentSpanId,omitempty"`
	ParentApplicationInstanceId int32     `protobuf:"varint,4,opt,name=parentApplicationInstanceId,proto3" json:"parentApplicationInstanceId,omitempty"`
	NetworkAddress              string    `protobuf:"bytes,5,opt,name=networkAddress,proto3" json:"networkAddress,omitempty"`
	NetworkAddressId            int32     `protobuf:"varint,6,opt,name=networkAddressId,proto3" json:"networkAddressId,omitempty"`
	EntryApplicationInstanceId  int32     `protobuf:"varint,7,opt,name=entryApplicationInstanceId,proto3" json:"entryApplicationInstanceId,omitempty"`
	EntryServiceName            string    `protobuf:"bytes,8,opt,name=entryServiceName,proto3" json:"entryServiceName,omitempty"`
	EntryServiceId              int32     `protobuf:"varint,9,opt,name=entryServiceId,proto3" json:"entryServiceId,omitempty"`
	ParentServiceName           string    `protobuf:"bytes,10,opt,name=parentServiceName,proto3" json:"parentServiceName,omitempty"`
	ParentServiceId             int32     `protobuf:"varint,11,opt,name=parentServiceId,proto3" json:"parentServiceId,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}  `json:"-"`
	XXX_unrecognized            []byte    `json:"-"`
	XXX_sizecache               int32     `json:"-"`
}

func (m *TraceSegmentReference) Reset()         { *m = TraceSegmentReference{} }
func (m *TraceSegmentReference) String() string { return proto.CompactTextString(m) }
func (*TraceSegmentReference) ProtoMessage()    {}
func (*TraceSegmentReference) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc055cab3bd8ed31, []int{3}
}

func (m *TraceSegmentReference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TraceSegmentReference.Unmarshal(m, b)
}
func (m *TraceSegmentReference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TraceSegmentReference.Marshal(b, m, deterministic)
}
func (m *TraceSegmentReference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TraceSegmentReference.Merge(m, src)
}
func (m *TraceSegmentReference) XXX_Size() int {
	return xxx_messageInfo_TraceSegmentReference.Size(m)
}
func (m *TraceSegmentReference) XXX_DiscardUnknown() {
	xxx_messageInfo_TraceSegmentReference.DiscardUnknown(m)
}

var xxx_messageInfo_TraceSegmentReference proto.InternalMessageInfo

func (m *TraceSegmentReference) GetRefType() RefType {
	if m != nil {
		return m.RefType
	}
	return RefType_CrossProcess
}

func (m *TraceSegmentReference) GetParentTraceSegmentId() *UniqueId {
	if m != nil {
		return m.ParentTraceSegmentId
	}
	return nil
}

func (m *TraceSegmentReference) GetParentSpanId() int32 {
	if m != nil {
		return m.ParentSpanId
	}
	return 0
}

func (m *TraceSegmentReference) GetParentApplicationInstanceId() int32 {
	if m != nil {
		return m.ParentApplicationInstanceId
	}
	return 0
}

func (m *TraceSegmentReference) GetNetworkAddress() string {
	if m != nil {
		return m.NetworkAddress
	}
	return ""
}

func (m *TraceSegmentReference) GetNetworkAddressId() int32 {
	if m != nil {
		return m.NetworkAddressId
	}
	return 0
}

func (m *TraceSegmentReference) GetEntryApplicationInstanceId() int32 {
	if m != nil {
		return m.EntryApplicationInstanceId
	}
	return 0
}

func (m *TraceSegmentReference) GetEntryServiceName() string {
	if m != nil {
		return m.EntryServiceName
	}
	return ""
}

func (m *TraceSegmentReference) GetEntryServiceId() int32 {
	if m != nil {
		return m.EntryServiceId
	}
	return 0
}

func (m *TraceSegmentReference) GetParentServiceName() string {
	if m != nil {
		return m.ParentServiceName
	}
	return ""
}

func (m *TraceSegmentReference) GetParentServiceId() int32 {
	if m != nil {
		return m.ParentServiceId
	}
	return 0
}

type SpanObject struct {
	SpanId               int32                    `protobuf:"varint,1,opt,name=spanId,proto3" json:"spanId,omitempty"`
	ParentSpanId         int32                    `protobuf:"varint,2,opt,name=parentSpanId,proto3" json:"parentSpanId,omitempty"`
	StartTime            int64                    `protobuf:"varint,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              int64                    `protobuf:"varint,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Refs                 []*TraceSegmentReference `protobuf:"bytes,5,rep,name=refs,proto3" json:"refs,omitempty"`
	OperationNameId      int32                    `protobuf:"varint,6,opt,name=operationNameId,proto3" json:"operationNameId,omitempty"`
	OperationName        string                   `protobuf:"bytes,7,opt,name=operationName,proto3" json:"operationName,omitempty"`
	PeerId               int32                    `protobuf:"varint,8,opt,name=peerId,proto3" json:"peerId,omitempty"`
	Peer                 string                   `protobuf:"bytes,9,opt,name=peer,proto3" json:"peer,omitempty"`
	SpanType             SpanType                 `protobuf:"varint,10,opt,name=spanType,proto3,enum=SpanType" json:"spanType,omitempty"`
	SpanLayer            SpanLayer                `protobuf:"varint,11,opt,name=spanLayer,proto3,enum=SpanLayer" json:"spanLayer,omitempty"`
	ComponentId          int32                    `protobuf:"varint,12,opt,name=componentId,proto3" json:"componentId,omitempty"`
	Component            string                   `protobuf:"bytes,13,opt,name=component,proto3" json:"component,omitempty"`
	IsError              bool                     `protobuf:"varint,14,opt,name=isError,proto3" json:"isError,omitempty"`
	Tags                 []*KeyWithStringValue    `protobuf:"bytes,15,rep,name=tags,proto3" json:"tags,omitempty"`
	Logs                 []*LogMessage            `protobuf:"bytes,16,rep,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *SpanObject) Reset()         { *m = SpanObject{} }
func (m *SpanObject) String() string { return proto.CompactTextString(m) }
func (*SpanObject) ProtoMessage()    {}
func (*SpanObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc055cab3bd8ed31, []int{4}
}

func (m *SpanObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpanObject.Unmarshal(m, b)
}
func (m *SpanObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpanObject.Marshal(b, m, deterministic)
}
func (m *SpanObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpanObject.Merge(m, src)
}
func (m *SpanObject) XXX_Size() int {
	return xxx_messageInfo_SpanObject.Size(m)
}
func (m *SpanObject) XXX_DiscardUnknown() {
	xxx_messageInfo_SpanObject.DiscardUnknown(m)
}

var xxx_messageInfo_SpanObject proto.InternalMessageInfo

func (m *SpanObject) GetSpanId() int32 {
	if m != nil {
		return m.SpanId
	}
	return 0
}

func (m *SpanObject) GetParentSpanId() int32 {
	if m != nil {
		return m.ParentSpanId
	}
	return 0
}

func (m *SpanObject) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *SpanObject) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *SpanObject) GetRefs() []*TraceSegmentReference {
	if m != nil {
		return m.Refs
	}
	return nil
}

func (m *SpanObject) GetOperationNameId() int32 {
	if m != nil {
		return m.OperationNameId
	}
	return 0
}

func (m *SpanObject) GetOperationName() string {
	if m != nil {
		return m.OperationName
	}
	return ""
}

func (m *SpanObject) GetPeerId() int32 {
	if m != nil {
		return m.PeerId
	}
	return 0
}

func (m *SpanObject) GetPeer() string {
	if m != nil {
		return m.Peer
	}
	return ""
}

func (m *SpanObject) GetSpanType() SpanType {
	if m != nil {
		return m.SpanType
	}
	return SpanType_Entry
}

func (m *SpanObject) GetSpanLayer() SpanLayer {
	if m != nil {
		return m.SpanLayer
	}
	return SpanLayer_Unknown
}

func (m *SpanObject) GetComponentId() int32 {
	if m != nil {
		return m.ComponentId
	}
	return 0
}

func (m *SpanObject) GetComponent() string {
	if m != nil {
		return m.Component
	}
	return ""
}

func (m *SpanObject) GetIsError() bool {
	if m != nil {
		return m.IsError
	}
	return false
}

func (m *SpanObject) GetTags() []*KeyWithStringValue {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *SpanObject) GetLogs() []*LogMessage {
	if m != nil {
		return m.Logs
	}
	return nil
}

type LogMessage struct {
	Time                 int64                 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Data                 []*KeyWithStringValue `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *LogMessage) Reset()         { *m = LogMessage{} }
func (m *LogMessage) String() string { return proto.CompactTextString(m) }
func (*LogMessage) ProtoMessage()    {}
func (*LogMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc055cab3bd8ed31, []int{5}
}

func (m *LogMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogMessage.Unmarshal(m, b)
}
func (m *LogMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogMessage.Marshal(b, m, deterministic)
}
func (m *LogMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogMessage.Merge(m, src)
}
func (m *LogMessage) XXX_Size() int {
	return xxx_messageInfo_LogMessage.Size(m)
}
func (m *LogMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_LogMessage.DiscardUnknown(m)
}

var xxx_messageInfo_LogMessage proto.InternalMessageInfo

func (m *LogMessage) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *LogMessage) GetData() []*KeyWithStringValue {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("RefType", RefType_name, RefType_value)
	proto.RegisterEnum("SpanLayer", SpanLayer_name, SpanLayer_value)
	proto.RegisterType((*UpstreamSegment)(nil), "UpstreamSegment")
	proto.RegisterType((*UniqueId)(nil), "UniqueId")
	proto.RegisterType((*TraceSegmentObject)(nil), "TraceSegmentObject")
	proto.RegisterType((*TraceSegmentReference)(nil), "TraceSegmentReference")
	proto.RegisterType((*SpanObject)(nil), "SpanObject")
	proto.RegisterType((*LogMessage)(nil), "LogMessage")
}

func init() { proto.RegisterFile("TraceSegmentService.proto", fileDescriptor_bc055cab3bd8ed31) }

var fileDescriptor_bc055cab3bd8ed31 = []byte{
	// 860 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x55, 0x5f, 0x8f, 0xdb, 0x44,
	0x10, 0xaf, 0x13, 0xe7, 0x12, 0x4f, 0xd2, 0x9c, 0xd9, 0xd2, 0xca, 0x1c, 0x48, 0x84, 0xa8, 0xd0,
	0xe8, 0x74, 0xb2, 0xc4, 0xc1, 0x2b, 0x88, 0x92, 0x82, 0x1a, 0x71, 0x2d, 0x61, 0x93, 0xa3, 0x6f,
	0x48, 0x7b, 0xf6, 0x5c, 0xce, 0x24, 0xde, 0x35, 0xbb, 0x5b, 0x4e, 0xe1, 0xbb, 0x20, 0xf1, 0xcc,
	0x67, 0xe3, 0x43, 0xa0, 0x1d, 0x3b, 0xff, 0xa3, 0x7b, 0xf3, 0xfc, 0xe6, 0xb7, 0xb3, 0x33, 0xbf,
	0xf1, 0xcc, 0xc2, 0x47, 0x53, 0x2d, 0x12, 0x9c, 0xe0, 0x2c, 0x47, 0x69, 0x27, 0xa8, 0xff, 0xcc,
	0x12, 0x8c, 0x0b, 0xad, 0xac, 0x3a, 0xeb, 0x0c, 0x55, 0x9e, 0x2b, 0x59, 0x59, 0xe1, 0x2b, 0x75,
	0x2f, 0x8d, 0xd5, 0x28, 0xf2, 0x0a, 0x89, 0x7e, 0xc2, 0xe5, 0xbb, 0xcc, 0xde, 0x4d, 0xac, 0xce,
	0xe4, 0xec, 0x57, 0xb1, 0x78, 0x5f, 0x9d, 0xec, 0xff, 0x06, 0xa7, 0xd7, 0x45, 0xc9, 0xad, 0x22,
	0xb3, 0x2f, 0xa1, 0x3b, 0x5b, 0xa8, 0x1b, 0xb1, 0xa0, 0xfb, 0x46, 0xa9, 0x89, 0xbc, 0x5e, 0x7d,
	0xd0, 0xbe, 0x0c, 0xe2, 0x6b, 0x99, 0xfd, 0xf1, 0x1e, 0x47, 0x29, 0xdf, 0x23, 0xb0, 0x08, 0x9a,
	0xa6, 0x3c, 0x1d, 0xd5, 0x7a, 0xde, 0xa0, 0xc3, 0x57, 0x66, 0xff, 0x39, 0xb4, 0x56, 0xa7, 0x1c,
	0x2b, 0x4b, 0xc7, 0x42, 0xdb, 0x32, 0x62, 0x9d, 0xaf, 0xcc, 0xfe, 0x7f, 0x1e, 0xb0, 0xed, 0xea,
	0x7e, 0xbe, 0xf9, 0x1d, 0x13, 0xca, 0xc4, 0x6e, 0xa1, 0xa3, 0x34, 0xf2, 0x7a, 0xde, 0x5e, 0x26,
	0xbb, 0x04, 0xf6, 0x19, 0x34, 0x4c, 0x21, 0xa4, 0x89, 0x6a, 0x94, 0x73, 0x3b, 0x9e, 0x14, 0x42,
	0x96, 0xe1, 0x78, 0xe9, 0x61, 0xcf, 0xe1, 0xb1, 0x28, 0x8a, 0x45, 0x96, 0x08, 0x9b, 0x29, 0x39,
	0x4a, 0xa3, 0x7a, 0xcf, 0x1b, 0x34, 0xf8, 0x2e, 0xc8, 0xbe, 0x86, 0xa7, 0xdb, 0x80, 0x34, 0x56,
	0x48, 0x57, 0x6c, 0xe4, 0x13, 0xfb, 0xb8, 0xd3, 0xc5, 0xce, 0xcc, 0x24, 0xfb, 0x0b, 0xaf, 0xb2,
	0x3c, 0xb3, 0x98, 0x46, 0x8d, 0x9e, 0x37, 0x68, 0xf1, 0x5d, 0xb0, 0xff, 0x8f, 0x0f, 0x4f, 0xb7,
	0xcb, 0xe5, 0x78, 0x8b, 0x1a, 0x65, 0x82, 0xac, 0x0f, 0x4d, 0x8d, 0xb7, 0xd3, 0x65, 0x81, 0x54,
	0x6a, 0xf7, 0xb2, 0x15, 0xf3, 0xd2, 0xe6, 0x2b, 0x07, 0xfb, 0x06, 0x3e, 0x2c, 0x84, 0x46, 0x69,
	0xa7, 0xbb, 0xda, 0xd4, 0xf6, 0xb5, 0x39, 0x4a, 0x63, 0x7d, 0xe8, 0x94, 0xb8, 0x53, 0x66, 0x5d,
	0xfd, 0x0e, 0xc6, 0xbe, 0x83, 0x8f, 0x4b, 0xfb, 0xe5, 0x03, 0x12, 0x3c, 0x44, 0x61, 0x5f, 0x40,
	0x57, 0xa2, 0xbd, 0x57, 0x7a, 0xfe, 0x32, 0x4d, 0x35, 0x1a, 0x43, 0x4a, 0x04, 0x7c, 0x0f, 0x65,
	0xe7, 0x10, 0xee, 0x22, 0xa3, 0x34, 0x3a, 0xa1, 0xf0, 0x07, 0x38, 0xfb, 0x16, 0xce, 0x50, 0x5a,
	0xbd, 0x3c, 0x9e, 0x54, 0x93, 0x4e, 0x3d, 0xc0, 0x70, 0x77, 0x91, 0xb7, 0x9a, 0x9d, 0xb7, 0x22,
	0xc7, 0xa8, 0x45, 0x59, 0x1d, 0xe0, 0x2e, 0xff, 0x6d, 0x6c, 0x94, 0x46, 0x01, 0xc5, 0xdf, 0x43,
	0xd9, 0x05, 0x7c, 0x50, 0x29, 0xb7, 0x15, 0x14, 0x28, 0xe8, 0xa1, 0x83, 0x0d, 0xe0, 0x74, 0x07,
	0x1c, 0xa5, 0x51, 0x9b, 0xc2, 0xee, 0xc3, 0xfd, 0xbf, 0x7d, 0x80, 0xcd, 0xaf, 0xcb, 0x9e, 0xc1,
	0x89, 0x29, 0xdb, 0xe5, 0x11, 0xbf, 0xb2, 0x0e, 0x9a, 0x59, 0x3b, 0xd2, 0xcc, 0x4f, 0x20, 0x30,
	0x56, 0x68, 0x3b, 0xcd, 0x72, 0xa4, 0x6e, 0xd7, 0xf9, 0x06, 0x70, 0x43, 0x89, 0x32, 0x25, 0x9f,
	0x4f, 0xbe, 0x95, 0xc9, 0xce, 0xc1, 0xd7, 0x78, 0xeb, 0x1a, 0xe7, 0x26, 0xe9, 0x59, 0x7c, 0xf4,
	0x8f, 0xe5, 0xc4, 0x71, 0x85, 0xa9, 0x02, 0x35, 0x29, 0xee, 0x2a, 0x5d, 0x77, 0x71, 0x1f, 0x76,
	0x13, 0xb2, 0x03, 0x51, 0xdf, 0x02, 0xbe, 0x0b, 0xba, 0x7a, 0x0b, 0x44, 0x3d, 0x4a, 0xa9, 0x41,
	0x0d, 0x5e, 0x59, 0x8c, 0x81, 0xef, 0xbe, 0xa8, 0x19, 0x01, 0xa7, 0x6f, 0xf6, 0x39, 0xb4, 0x9c,
	0x1a, 0x34, 0x34, 0x40, 0x43, 0x13, 0xd0, 0xd4, 0xd3, 0xd4, 0xac, 0x5d, 0x6c, 0x00, 0x81, 0xfb,
	0xbe, 0x12, 0x4b, 0xd4, 0xa4, 0x7a, 0xf7, 0x12, 0x88, 0x47, 0x08, 0xdf, 0x38, 0x59, 0x0f, 0xda,
	0x89, 0xca, 0x0b, 0x25, 0xcb, 0xb9, 0xea, 0x50, 0x06, 0xdb, 0x90, 0x93, 0x74, 0x6d, 0x46, 0x8f,
	0x29, 0x97, 0x0d, 0x40, 0x7b, 0xce, 0xfc, 0xa0, 0xb5, 0xd2, 0x51, 0x97, 0xc6, 0x7f, 0x65, 0xb2,
	0x17, 0xe0, 0x5b, 0x31, 0x33, 0xd1, 0x29, 0x49, 0xfa, 0x24, 0x3e, 0x5c, 0xcb, 0x9c, 0x08, 0xec,
	0x53, 0xf0, 0x17, 0x6a, 0x66, 0xa2, 0xb0, 0xda, 0x62, 0x57, 0x6a, 0xf6, 0x06, 0x8d, 0x11, 0x33,
	0xe4, 0xe4, 0xe8, 0x8f, 0x00, 0x36, 0x98, 0x93, 0xc5, 0xba, 0x0e, 0x7a, 0xd4, 0x41, 0xfa, 0x76,
	0x77, 0xa5, 0xc2, 0x8a, 0x6a, 0x11, 0x1e, 0xbf, 0xcb, 0x11, 0xce, 0x2f, 0xa0, 0x59, 0xed, 0x18,
	0x16, 0x42, 0x67, 0xa8, 0x95, 0x31, 0x63, 0xad, 0x12, 0x34, 0x26, 0x7c, 0xc4, 0x4e, 0xa1, 0x4d,
	0xc8, 0xf4, 0x4e, 0xa3, 0x48, 0x43, 0xef, 0xfc, 0x1a, 0x82, 0xb5, 0x68, 0xac, 0x0d, 0xcd, 0x6b,
	0x39, 0x97, 0xea, 0x5e, 0x86, 0x8f, 0x58, 0x07, 0x5a, 0xaf, 0x84, 0x15, 0x37, 0xc2, 0x60, 0xe8,
	0xb9, 0x50, 0x7c, 0x3c, 0xfc, 0x51, 0x8b, 0x1c, 0xdd, 0x14, 0x87, 0x35, 0xd6, 0x02, 0xff, 0xb5,
	0xb5, 0x45, 0x58, 0x67, 0x27, 0x50, 0x7b, 0xf3, 0x4b, 0xe8, 0xb3, 0x00, 0x1a, 0x43, 0x91, 0xdc,
	0x61, 0xd8, 0xb8, 0x1c, 0xc2, 0x93, 0x23, 0xcf, 0x1b, 0xbb, 0x80, 0x66, 0xa2, 0x16, 0x0b, 0x37,
	0x02, 0x61, 0xbc, 0xf7, 0x50, 0x9d, 0xb5, 0xe3, 0xcd, 0x43, 0xd7, 0x7f, 0x34, 0xf0, 0xbe, 0x7f,
	0x0d, 0x2f, 0x94, 0x9e, 0xc5, 0xa2, 0x70, 0x41, 0x63, 0x33, 0x5f, 0xde, 0x8b, 0xc5, 0x3c, 0x93,
	0x0e, 0xc9, 0xe3, 0x6a, 0x9d, 0x94, 0xef, 0xde, 0xd8, 0xfb, 0xb7, 0x76, 0x36, 0x99, 0x2f, 0xdf,
	0x55, 0x84, 0xb7, 0xa5, 0x73, 0xec, 0x7c, 0x89, 0x5a, 0xdc, 0x9c, 0x10, 0xeb, 0xab, 0xff, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xe7, 0xe9, 0x43, 0x81, 0x74, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TraceSegmentServiceClient is the client API for TraceSegmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TraceSegmentServiceClient interface {
	Collect(ctx context.Context, opts ...grpc.CallOption) (TraceSegmentService_CollectClient, error)
}

type traceSegmentServiceClient struct {
	cc *grpc.ClientConn
}

func NewTraceSegmentServiceClient(cc *grpc.ClientConn) TraceSegmentServiceClient {
	return &traceSegmentServiceClient{cc}
}

func (c *traceSegmentServiceClient) Collect(ctx context.Context, opts ...grpc.CallOption) (TraceSegmentService_CollectClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TraceSegmentService_serviceDesc.Streams[0], "/TraceSegmentService/collect", opts...)
	if err != nil {
		return nil, err
	}
	x := &traceSegmentServiceCollectClient{stream}
	return x, nil
}

type TraceSegmentService_CollectClient interface {
	Send(*UpstreamSegment) error
	CloseAndRecv() (*Downstream, error)
	grpc.ClientStream
}

type traceSegmentServiceCollectClient struct {
	grpc.ClientStream
}

func (x *traceSegmentServiceCollectClient) Send(m *UpstreamSegment) error {
	return x.ClientStream.SendMsg(m)
}

func (x *traceSegmentServiceCollectClient) CloseAndRecv() (*Downstream, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Downstream)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TraceSegmentServiceServer is the server API for TraceSegmentService service.
type TraceSegmentServiceServer interface {
	Collect(TraceSegmentService_CollectServer) error
}

func RegisterTraceSegmentServiceServer(s *grpc.Server, srv TraceSegmentServiceServer) {
	s.RegisterService(&_TraceSegmentService_serviceDesc, srv)
}

func _TraceSegmentService_Collect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TraceSegmentServiceServer).Collect(&traceSegmentServiceCollectServer{stream})
}

type TraceSegmentService_CollectServer interface {
	SendAndClose(*Downstream) error
	Recv() (*UpstreamSegment, error)
	grpc.ServerStream
}

type traceSegmentServiceCollectServer struct {
	grpc.ServerStream
}

func (x *traceSegmentServiceCollectServer) SendAndClose(m *Downstream) error {
	return x.ServerStream.SendMsg(m)
}

func (x *traceSegmentServiceCollectServer) Recv() (*UpstreamSegment, error) {
	m := new(UpstreamSegment)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _TraceSegmentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TraceSegmentService",
	HandlerType: (*TraceSegmentServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "collect",
			Handler:       _TraceSegmentService_Collect_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "TraceSegmentService.proto",
}
