// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Common.proto

package skyproto

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SpanType int32

const (
	SpanType_Entry SpanType = 0
	SpanType_Exit  SpanType = 1
	SpanType_Local SpanType = 2
)

var SpanType_name = map[int32]string{
	0: "Entry",
	1: "Exit",
	2: "Local",
}

var SpanType_value = map[string]int32{
	"Entry": 0,
	"Exit":  1,
	"Local": 2,
}

func (x SpanType) String() string {
	return proto.EnumName(SpanType_name, int32(x))
}

func (SpanType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ee72d9a89737215c, []int{0}
}

func init() {
	proto.RegisterEnum("SpanType", SpanType_name, SpanType_value)
}

func init() { proto.RegisterFile("Common.proto", fileDescriptor_ee72d9a89737215c) }

var fileDescriptor_ee72d9a89737215c = []byte{
	// 85 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x71, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xd2, 0xe2, 0xe2, 0x08, 0x2e, 0x48, 0xcc,
	0x0b, 0xa9, 0x2c, 0x48, 0x15, 0xe2, 0xe4, 0x62, 0x75, 0xcd, 0x2b, 0x29, 0xaa, 0x14, 0x60, 0x10,
	0xe2, 0xe0, 0x62, 0x71, 0xad, 0xc8, 0x2c, 0x11, 0x60, 0x04, 0x09, 0xfa, 0xe4, 0x27, 0x27, 0xe6,
	0x08, 0x30, 0x25, 0xb1, 0x81, 0xb5, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x24, 0xd3,
	0x45, 0x42, 0x00, 0x00, 0x00,
}
